name: quick_remote_pc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  crypto: ^3.0.7
  ffi: ^2.2.0
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  qr_flutter: ^4.1.0
  screen_retriever: ^0.2.0
  win32: ^6.0.0
  window_manager: ^0.5.1
  nsd: ^2.3.1
  google_fonts: ^8.2.1
  path_provider: ^2.1.6
  quick_remote_shared:
    path: ../packages/quick_remote_shared
  shared_preferences: ^2.5.5
  dbus: ^0.8.0
  path: ^1.9.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/linux/

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/images/logo.png"
